app:
  env: local # local, development, production

user: # on what host and port the user service should run
  host: # host to connect to user service
  port: 5000 # port to connect to user service

inventory: # on what host and port the inventory service should run
  host: # host to connect to inventory service
  port: 5001 # port to connect to inventory service

order: # on what host and port the order service should run
  host: # host to connect to order service
  port: 5002 # port to connect to order service

gateway: # call address to other services and external once
  user:
    host: user-service # the docker alias to connect to user service internally
    port: 50051 # port to connect to user service

  inventory:
    host: inventory-service # the docker alias to connect to inventory service internally
    port: 50052 # port to connect to inventory service

log:
  level: info # debug, info, warning, error, fatal, panic
  dir: logs # directory to store logs
  write_to_file: true # write logs to file
  compress_log_files: false # compress log files
  max_age: 7 # days
  max_size: 100 # MB